### ISSUE TITLE
Inversion image page 6

### ISSUE THREAD

**Issue by juans64** [juliengiraud/Methode-Fridrich#1]
![E383ED0B-EA9F-4A75-A76E-E58A59605B14](https://user-images.githubusercontent.com/81250562/196036939-c2a5674a-4a13-4c97-800c-7688415db726.jpeg)

Bravo pour le doc !
Il y a une erreur sur le *.pdf, en page 6 : les l et l2 sont inversés

**Comment by juliengiraud** [comment]
Bonjour, merci beaucoup d'avoir reporté cette issue ! Ce n'est que deux ans plus tard que je la découvre mais cette erreur est enfin corrigée :)
