### ISSUE TITLE
Problème de compréhension

### ISSUE THREAD

**Issue by Sebwap** [juliengiraud/Methode-Fridrich#2]
Hello,

Je m'intéresse à la méthode Fridrich depuis quelques jours et j'ai téléchargé votre guide; merci beaucoup pour la quantité de travail que cela représente.

J'ai une question cependant: parfois, j'ai l'impression qu'il y a des erreurs dans la notation des algorithmes avec une confusion entre les faces F et L.

Par exemple, si je regarde dans le guide l'algo N°25 correspondant à l'étape des F2L:
![F2L n°25](https://i.ibb.co/c2PW3bP/algo-25.png)

Pour moi l'algo serait plutôt U' F' U F , la face bleu étant celle "de face", nommée F.

Plus qu'une erreur de votre part, je pense que c'est un problème de compréhension des notations de ma part.

Pouvez-vous m'éclairer ?

Encore merci pour votre travail !

**Comment by juliengiraud** [comment]
Bonjour,

Je m'excuse d'avoir mis si longtemps à répondre, ce n'est qu'avec 2 ans de retard que je découvre que 2 issues ont été ouvertes sur mon projet 😅
Je pense que depuis le temps la question n'est plus d'actualité mais je vais y répondre quand même :)

Sur cet exemple, ta proposition et la mienne sont exactement la même suite de mouvements, mais exécutés depuis deux *points de vue* différents. Si le bleu est face à nous, `F` qualifie la face bleue. Si le rouge est face à nous, `L` qualifie la face bleue (et `U` reste `U`, ce changement de point de vue n'a pas d'impact sur les faces du haut et du bas `U/D`).

J'ai fait le choix de privilégier les mouvements en `R/U` car ils sont plus faciles à exécuter, puis par miroir les mouvements en `L/U`, puis enfin les autres mouvements (`F/D/B`). C'est pourquoi ici j'ai proposé la solution en `L/U`.
Il s'agit d'un choix qui est globalement pratique mais qui ne prétend pas être "optimal".
Par exemple, si je voulais garder la face bleue comme référence, plutôt que de faire `U' F' U F` je préfère changer de point de vue avec `D → F` pour utiliser `U R' U' R` qui est une solution en `R/U`.

Plusieurs solutions alternatives existent pour chaque situation au Rubik's Cube, le tout est de choisir celle qu'on préfère !

En espérant avoir répondu à ta question,
Julien
